// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeNiagaraLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UUnrealBridgeNiagaraLibrary::IsNiagaraApiAvailable()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::IsNiagaraApiAvailable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeNiagaraLibrary::GetLastNiagaraError()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::GetLastNiagaraError requires UE 5.7+ — call ignored on this engine version"));
	return TEXT("Niagara authoring API requires Unreal Engine 5.7+");
}

TArray<FBridgeNiagaraTemplateInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraTemplates(const FString& AssetType, const FString& Query, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraTemplates requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraTemplateInfo>{};
}

TArray<FBridgeNiagaraScriptInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraScripts(const FString& Usage, const FString& Query, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraScripts requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraScriptInfo>{};
}

FBridgeNiagaraScriptInfo UUnrealBridgeNiagaraLibrary::GetNiagaraScriptInfo(const FString& ScriptPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::GetNiagaraScriptInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraScriptInfo{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::CreateNiagaraSystem(const FString& AssetPath, const FString& TemplateSystemPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::CreateNiagaraSystem requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::CreateNiagaraEmitter(const FString& AssetPath, const FString& TemplateEmitterPath, bool bAddDefaultModulesAndRenderer, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::CreateNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::CreateNiagaraSystemFromRecipe(const FString& AssetPath, const FBridgeNiagaraSystemRecipe& Recipe, bool bCompile, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::CreateNiagaraSystemFromRecipe requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::DeleteNiagaraAsset(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::DeleteNiagaraAsset requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraSystemInfo UUnrealBridgeNiagaraLibrary::GetNiagaraSystemInfo(const FString& SystemPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::GetNiagaraSystemInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraSystemInfo{};
}

TArray<FBridgeNiagaraEmitterInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraEmitters(const FString& SystemPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraEmitters requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraEmitterInfo>{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::AddNiagaraEmitter(const FString& SystemPath, const FString& Name, const FString& EmitterAssetOrTemplatePath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::AddNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::DuplicateNiagaraEmitter(const FString& SystemPath, const FString& EmitterIdOrName, const FString& NewName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::DuplicateNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

bool UUnrealBridgeNiagaraLibrary::RemoveNiagaraEmitter(const FString& SystemPath, const FString& EmitterIdOrName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::RemoveNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::RenameNiagaraEmitter(const FString& SystemPath, const FString& EmitterIdOrName, const FString& NewName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::RenameNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraEmitterEnabled(const FString& SystemPath, const FString& EmitterIdOrName, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraEmitterEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraEmitterProperties(const FString& SystemPath, const FString& EmitterIdOrName, bool bLocalSpace, const FString& SimTarget, bool bDeterministic, int32 RandomSeed, bool bUseFixedBounds, const FBox& FixedBounds, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraEmitterProperties requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeNiagaraModuleInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraModules(const FString& SystemPath, const FString& EmitterIdOrName, const FString& Usage)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraModules requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraModuleInfo>{};
}

TArray<FBridgeNiagaraModuleInputInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraModuleInputs(const FString& SystemPath, const FString& ModuleId, bool bIncludeHidden)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraModuleInputs requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraModuleInputInfo>{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::AddNiagaraModule(const FString& SystemPath, const FString& EmitterIdOrName, const FString& Usage, const FString& ScriptPath, const FString& SuggestedName, int32 Index, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::AddNiagaraModule requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

bool UUnrealBridgeNiagaraLibrary::RemoveNiagaraModule(const FString& SystemPath, const FString& ModuleId, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::RemoveNiagaraModule requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraModuleEnabled(const FString& SystemPath, const FString& ModuleId, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraModuleEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraModuleInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& Value, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraModuleInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::LinkNiagaraModuleInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& LinkedParameter, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::LinkNiagaraModuleInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::SetNiagaraModuleDynamicInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& DynamicInputScriptPath, const FString& SuggestedName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraModuleDynamicInput requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraModuleObjectInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& ObjectPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraModuleObjectInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::SetNiagaraModuleDataInterfaceInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& DataInterfaceClassPath, const TArray<FBridgeNiagaraPropertyValue>& Properties, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraModuleDataInterfaceInput requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

TArray<FBridgeNiagaraPropertyInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraModuleInputObjectProperties(const FString& SystemPath, const FString& ModuleId, const FString& InputName, bool bIncludeAdvanced)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraModuleInputObjectProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraPropertyInfo>{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraModuleInputObjectProperty(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& PropertyName, const FString& Value, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraModuleInputObjectProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::ResetNiagaraModuleInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ResetNiagaraModuleInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::AddNiagaraParameterAssignment(const FString& SystemPath, const FString& EmitterIdOrName, const FString& Usage, const FString& ParameterName, const FString& Type, const FString& Value, int32 Index, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::AddNiagaraParameterAssignment requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

TArray<FBridgeNiagaraParameterInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraUserParameters(const FString& SystemPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraUserParameters requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraParameterInfo>{};
}

bool UUnrealBridgeNiagaraLibrary::AddNiagaraUserParameter(const FString& SystemPath, const FString& Name, const FString& Type, const FString& DefaultValue, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::AddNiagaraUserParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraUserParameterDefault(const FString& SystemPath, const FString& Name, const FString& Value, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraUserParameterDefault requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::RenameNiagaraUserParameter(const FString& SystemPath, const FString& OldName, const FString& NewName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::RenameNiagaraUserParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::RemoveNiagaraUserParameter(const FString& SystemPath, const FString& Name, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::RemoveNiagaraUserParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeNiagaraRendererInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraRenderers(const FString& SystemPath, const FString& EmitterIdOrName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraRenderers requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraRendererInfo>{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::AddNiagaraRenderer(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererType, const FString& Name, const FString& MaterialPath, const FString& MeshPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::AddNiagaraRenderer requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

bool UUnrealBridgeNiagaraLibrary::RemoveNiagaraRenderer(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::RemoveNiagaraRenderer requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraRendererEnabled(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraRendererEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeNiagaraPropertyInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraRendererProperties(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, bool bIncludeAdvanced)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraRendererProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraPropertyInfo>{};
}

FString UUnrealBridgeNiagaraLibrary::GetNiagaraRendererProperty(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, const FString& PropertyName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::GetNiagaraRendererProperty requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraRendererProperty(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, const FString& PropertyName, const FString& Value, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraRendererProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraRendererMaterial(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, const FString& MaterialPath, int32 MaterialIndex, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraRendererMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraRendererBinding(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, const FString& BindingProperty, const FString& VariableName, const FString& SourceMode, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraRendererBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraSystemWarmup(const FString& SystemPath, float WarmupTime, float TickDelta, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraSystemWarmup requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraSystemFixedBounds(const FString& SystemPath, bool bEnabled, const FBox& Bounds, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraSystemFixedBounds requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraSystemEffectType(const FString& SystemPath, const FString& EffectTypePath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraSystemEffectType requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeNiagaraCompileResult UUnrealBridgeNiagaraLibrary::CompileNiagaraSystem(const FString& SystemPath, bool bForce, bool bWaitForGpuShaders, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::CompileNiagaraSystem requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraCompileResult{};
}

FBridgeNiagaraCompileResult UUnrealBridgeNiagaraLibrary::GetNiagaraCompileDiagnostics(const FString& SystemPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::GetNiagaraCompileDiagnostics requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraCompileResult{};
}

FBridgeNiagaraAuditResult UUnrealBridgeNiagaraLibrary::ValidateNiagaraSystem(const FString& SystemPath, bool bCheckMaterials, bool bCheckBounds, int32 MaxEmitters, int32 MaxRenderersPerEmitter, int32 MaxModulesPerEmitter)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ValidateNiagaraSystem requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraAuditResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::CreateWeaponTrailEffect(const FString& AssetPath, const FString& Style, const FString& MaterialPath, const FLinearColor& Color, float Width, float Lifetime, float SpawnRate, bool bLocalSpace, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::CreateWeaponTrailEffect requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::CreateSparkEffect(const FString& AssetPath, const FString& Style, const FString& MaterialPath, const FLinearColor& Color, int32 Count, float Speed, float Lifetime, float Gravity, bool bCollision, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::CreateSparkEffect requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::CreateExplosionEffect(const FString& AssetPath, const FString& Style, const FString& MaterialPath, const FLinearColor& CoreColor, float Scale, float Duration, int32 DebrisCount, bool bShockwave, bool bLight, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::CreateExplosionEffect requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::CreateDissolveEffect(const FString& AssetPath, const FString& Style, const FString& MaterialPath, const FLinearColor& Color, int32 Count, float Duration, float Radius, const FVector& Direction, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::CreateDissolveEffect requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

FBridgeNiagaraOperationResult UUnrealBridgeNiagaraLibrary::SpawnNiagaraPreview(const FString& SystemPath, const FTransform& Transform, bool bAutoActivate, bool bResetOnChange)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SpawnNiagaraPreview requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraOperationResult{};
}

TArray<FBridgeNiagaraPreviewInfo> UUnrealBridgeNiagaraLibrary::ListNiagaraPreviews()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ListNiagaraPreviews requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeNiagaraPreviewInfo>{};
}

FBridgeNiagaraPreviewInfo UUnrealBridgeNiagaraLibrary::GetNiagaraPreviewInfo(const FString& Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::GetNiagaraPreviewInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNiagaraPreviewInfo{};
}

bool UUnrealBridgeNiagaraLibrary::AdvanceNiagaraPreview(const FString& Handle, float Seconds, float TickDelta)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::AdvanceNiagaraPreview requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraPreviewTransform(const FString& Handle, const FTransform& Transform, bool bTeleport)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraPreviewTransform requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::SetNiagaraPreviewVariable(const FString& Handle, const FString& Name, const FString& Type, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::SetNiagaraPreviewVariable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::ControlNiagaraPreview(const FString& Handle, const FString& Action)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::ControlNiagaraPreview requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeNiagaraLibrary::RemoveNiagaraPreview(const FString& Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::RemoveNiagaraPreview requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UUnrealBridgeNiagaraLibrary::RemoveAllNiagaraPreviews()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNiagaraLibrary::RemoveAllNiagaraPreviews requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
