// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeRigLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UUnrealBridgeRigLibrary::IsRigApiAvailable()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::IsRigApiAvailable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeRigLibrary::GetLastRigError()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::GetLastRigError requires UE 5.7+ — call ignored on this engine version"));
	return TEXT("Control Rig / IK Rig authoring API requires Unreal Engine 5.7+");
}

TArray<FBridgeRigTypeInfo> UUnrealBridgeRigLibrary::ListRigTypes(const FString& Kind, const FString& Query, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListRigTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeRigTypeInfo>{};
}

FBridgeRigOperationResult UUnrealBridgeRigLibrary::CreateControlRig(const FString& AssetPath, const FString& SourceSkeletalAssetPath, bool bModularRig, bool bImportCurves)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::CreateControlRig requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigOperationResult{};
}

FBridgeControlRigInfo UUnrealBridgeRigLibrary::GetControlRigInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::GetControlRigInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeControlRigInfo{};
}

TArray<FBridgeRigElementInfo> UUnrealBridgeRigLibrary::ListControlRigElements(const FString& AssetPath, const FString& ElementType)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListControlRigElements requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeRigElementInfo>{};
}

bool UUnrealBridgeRigLibrary::ImportControlRigHierarchy(const FString& AssetPath, const FString& SourceSkeletalAssetPath, bool bReplaceExisting, bool bImportCurves)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ImportControlRigHierarchy requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeRigLibrary::AddControlRigBone(const FString& AssetPath, const FString& Name, const FString& ParentName, const FString& ParentType, const FTransform& Transform, bool bGlobalTransform, bool bImportedBone)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigBone requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::AddControlRigNull(const FString& AssetPath, const FString& Name, const FString& ParentName, const FString& ParentType, const FTransform& Transform, bool bGlobalTransform)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigNull requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::AddControlRigControl(const FString& AssetPath, const FString& Name, const FString& ParentName, const FString& ParentType, const FString& ControlType, const FString& InitialValue, const FTransform& OffsetTransform, const FTransform& ShapeTransform, const FString& ShapeName, const FLinearColor& ShapeColor, bool bAnimatable)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigControl requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::AddControlRigCurve(const FString& AssetPath, const FString& Name, float Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigCurve requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::AddControlRigConnector(const FString& AssetPath, const FString& Name, const FString& ConnectorType, const FString& Description, bool bOptional, bool bArray)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigConnector requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeRigLibrary::RemoveControlRigElement(const FString& AssetPath, const FString& Name, const FString& ElementType)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveControlRigElement requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeRigLibrary::RenameControlRigElement(const FString& AssetPath, const FString& Name, const FString& ElementType, const FString& NewName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RenameControlRigElement requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeRigLibrary::ReparentControlRigElement(const FString& AssetPath, const FString& Name, const FString& ElementType, const FString& ParentName, const FString& ParentType, bool bMaintainGlobalTransform)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ReparentControlRigElement requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetControlRigElementTransform(const FString& AssetPath, const FString& Name, const FString& ElementType, const FTransform& Transform, bool bGlobalTransform, bool bInitial, bool bAffectChildren)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetControlRigElementTransform requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetControlRigControlShape(const FString& AssetPath, const FString& ControlName, const FString& ShapeName, const FLinearColor& ShapeColor, bool bVisible)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetControlRigControlShape requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::AddControlRigElementTag(const FString& AssetPath, const FString& Name, const FString& ElementType, const FString& Tag)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigElementTag requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::RemoveControlRigElementTag(const FString& AssetPath, const FString& Name, const FString& ElementType, const FString& Tag)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveControlRigElementTag requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeRigPropertyInfo> UUnrealBridgeRigLibrary::ListControlRigControlProperties(const FString& AssetPath, const FString& ControlName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListControlRigControlProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeRigPropertyInfo>{};
}

FBridgeRigPropertyResult UUnrealBridgeRigLibrary::GetControlRigControlProperty(const FString& AssetPath, const FString& ControlName, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::GetControlRigControlProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigPropertyResult{};
}

bool UUnrealBridgeRigLibrary::SetControlRigControlProperty(const FString& AssetPath, const FString& ControlName, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetControlRigControlProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeRigVMGraphInfo> UUnrealBridgeRigLibrary::ListControlRigGraphs(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListControlRigGraphs requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeRigVMGraphInfo>{};
}

TArray<FBridgeRigVMNodeInfo> UUnrealBridgeRigLibrary::ListControlRigNodes(const FString& AssetPath, const FString& GraphName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListControlRigNodes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeRigVMNodeInfo>{};
}

TArray<FBridgeRigVMLinkInfo> UUnrealBridgeRigLibrary::ListControlRigLinks(const FString& AssetPath, const FString& GraphName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListControlRigLinks requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeRigVMLinkInfo>{};
}

FString UUnrealBridgeRigLibrary::AddControlRigMemberVariable(const FString& AssetPath, const FString& Name, const FString& CPPType, const FString& DefaultValue, bool bPublic, bool bReadOnly)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigMemberVariable requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeRigLibrary::RemoveControlRigMemberVariable(const FString& AssetPath, const FString& Name)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveControlRigMemberVariable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeRigLibrary::AddControlRigUnitNode(const FString& AssetPath, const FString& GraphName, const FString& UnitStructPath, const FString& MethodName, const FVector2D& Position, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigUnitNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::AddControlRigTemplateNode(const FString& AssetPath, const FString& GraphName, const FString& Notation, const FVector2D& Position, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigTemplateNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::AddControlRigVariableNode(const FString& AssetPath, const FString& GraphName, const FString& VariableName, const FString& CPPType, const FString& CPPTypeObjectPath, bool bGetter, const FString& DefaultValue, const FVector2D& Position, const FString& NodeName, bool bCreateMemberVariable)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigVariableNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::AddControlRigCommentNode(const FString& AssetPath, const FString& GraphName, const FString& CommentText, const FVector2D& Position, const FVector2D& Size, const FLinearColor& Color, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigCommentNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::AddControlRigBranchNode(const FString& AssetPath, const FString& GraphName, const FVector2D& Position, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddControlRigBranchNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeRigLibrary::RemoveControlRigNode(const FString& AssetPath, const FString& GraphName, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveControlRigNode requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetControlRigNodePosition(const FString& AssetPath, const FString& GraphName, const FString& NodeName, const FVector2D& Position)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetControlRigNodePosition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetControlRigPinDefaultValue(const FString& AssetPath, const FString& GraphName, const FString& PinPath, const FString& DefaultValue, bool bResizeArrays)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetControlRigPinDefaultValue requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::ConnectControlRigPins(const FString& AssetPath, const FString& GraphName, const FString& OutputPinPath, const FString& InputPinPath, bool bCreateCastNode)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ConnectControlRigPins requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::DisconnectControlRigPins(const FString& AssetPath, const FString& GraphName, const FString& OutputPinPath, const FString& InputPinPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::DisconnectControlRigPins requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeRigLayoutResult UUnrealBridgeRigLibrary::AutoLayoutControlRigGraph(const FString& AssetPath, const FString& GraphName, float HorizontalSpacing, float VerticalSpacing)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AutoLayoutControlRigGraph requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigLayoutResult{};
}

FBridgeRigValidationReport UUnrealBridgeRigLibrary::CompileControlRig(const FString& AssetPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::CompileControlRig requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigValidationReport{};
}

FBridgeRigValidationReport UUnrealBridgeRigLibrary::ValidateControlRig(const FString& AssetPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ValidateControlRig requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigValidationReport{};
}

FBridgeControlRigEvaluationResult UUnrealBridgeRigLibrary::EvaluateControlRig(const FString& AssetPath, const FString& EventName, const TArray<FBridgeRigNamedTransform>& InputControls)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::EvaluateControlRig requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeControlRigEvaluationResult{};
}

FBridgeRigOperationResult UUnrealBridgeRigLibrary::CreateIKRig(const FString& AssetPath, const FString& SkeletalMeshPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::CreateIKRig requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigOperationResult{};
}

FBridgeIKRigInfo UUnrealBridgeRigLibrary::GetIKRigInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::GetIKRigInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeIKRigInfo{};
}

TArray<FBridgeIKSolverInfo> UUnrealBridgeRigLibrary::ListIKRigSolvers(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRigSolvers requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeIKSolverInfo>{};
}

TArray<FBridgeIKGoalInfo> UUnrealBridgeRigLibrary::ListIKRigGoals(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRigGoals requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeIKGoalInfo>{};
}

TArray<FBridgeIKChainInfo> UUnrealBridgeRigLibrary::ListIKRigRetargetChains(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRigRetargetChains requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeIKChainInfo>{};
}

int32 UUnrealBridgeRigLibrary::AddIKRigSolver(const FString& AssetPath, const FString& SolverTypePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddIKRigSolver requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UUnrealBridgeRigLibrary::RemoveIKRigSolver(const FString& AssetPath, int32 SolverIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveIKRigSolver requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::MoveIKRigSolver(const FString& AssetPath, int32 SolverIndex, int32 TargetIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::MoveIKRigSolver requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetIKRigSolverEnabled(const FString& AssetPath, int32 SolverIndex, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRigSolverEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetIKRigSolverBones(const FString& AssetPath, int32 SolverIndex, const FString& StartBone, const FString& EndBone)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRigSolverBones requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeRigLibrary::AddIKRigGoal(const FString& AssetPath, const FString& GoalName, const FString& BoneName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddIKRigGoal requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeRigLibrary::RemoveIKRigGoal(const FString& AssetPath, const FString& GoalName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveIKRigGoal requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::ConnectIKRigGoalToSolver(const FString& AssetPath, const FString& GoalName, int32 SolverIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ConnectIKRigGoalToSolver requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::DisconnectIKRigGoalFromSolver(const FString& AssetPath, const FString& GoalName, int32 SolverIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::DisconnectIKRigGoalFromSolver requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeRigLibrary::AddIKRigRetargetChain(const FString& AssetPath, const FString& ChainName, const FString& StartBone, const FString& EndBone, const FString& GoalName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddIKRigRetargetChain requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeRigLibrary::RemoveIKRigRetargetChain(const FString& AssetPath, const FString& ChainName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveIKRigRetargetChain requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeRigLibrary::RenameIKRigRetargetChain(const FString& AssetPath, const FString& ChainName, const FString& NewName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RenameIKRigRetargetChain requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeRigLibrary::SetIKRigRetargetRoot(const FString& AssetPath, const FString& RootBoneName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRigRetargetRoot requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetIKRigBoneExcluded(const FString& AssetPath, const FString& BoneName, bool bExcluded)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRigBoneExcluded requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::ApplyIKRigAutoSetup(const FString& AssetPath, bool bRetargetDefinition, bool bFullBodyIK)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ApplyIKRigAutoSetup requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeRigPropertyInfo> UUnrealBridgeRigLibrary::ListIKRigProperties(const FString& AssetPath, const FString& TargetKind, int32 SolverIndex, const FString& TargetName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRigProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeRigPropertyInfo>{};
}

FBridgeRigPropertyResult UUnrealBridgeRigLibrary::GetIKRigProperty(const FString& AssetPath, const FString& TargetKind, int32 SolverIndex, const FString& TargetName, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::GetIKRigProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigPropertyResult{};
}

bool UUnrealBridgeRigLibrary::SetIKRigProperty(const FString& AssetPath, const FString& TargetKind, int32 SolverIndex, const FString& TargetName, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRigProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeRigValidationReport UUnrealBridgeRigLibrary::ValidateIKRig(const FString& AssetPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ValidateIKRig requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigValidationReport{};
}

FBridgeRigOperationResult UUnrealBridgeRigLibrary::CreateIKRetargeter(const FString& AssetPath, const FString& SourceIKRigPath, const FString& TargetIKRigPath, const FString& SourcePreviewMeshPath, const FString& TargetPreviewMeshPath, bool bAddDefaultOps)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::CreateIKRetargeter requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigOperationResult{};
}

FBridgeIKRetargeterInfo UUnrealBridgeRigLibrary::GetIKRetargeterInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::GetIKRetargeterInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeIKRetargeterInfo{};
}

bool UUnrealBridgeRigLibrary::ConfigureIKRetargeterAssets(const FString& AssetPath, const FString& SourceIKRigPath, const FString& TargetIKRigPath, const FString& SourcePreviewMeshPath, const FString& TargetPreviewMeshPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ConfigureIKRetargeterAssets requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeIKRetargetOpInfo> UUnrealBridgeRigLibrary::ListIKRetargetOps(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRetargetOps requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeIKRetargetOpInfo>{};
}

int32 UUnrealBridgeRigLibrary::AddIKRetargetOp(const FString& AssetPath, const FString& OpTypePath, const FString& OpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddIKRetargetOp requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UUnrealBridgeRigLibrary::AddDefaultIKRetargetOps(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AddDefaultIKRetargetOps requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::RemoveIKRetargetOp(const FString& AssetPath, int32 OpIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveIKRetargetOp requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::MoveIKRetargetOp(const FString& AssetPath, int32 OpIndex, int32 TargetIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::MoveIKRetargetOp requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetIKRetargetOpEnabled(const FString& AssetPath, int32 OpIndex, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRetargetOpEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetIKRetargetOpParent(const FString& AssetPath, const FString& ChildOpName, const FString& ParentOpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRetargetOpParent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::AutoMapIKRetargetChains(const FString& AssetPath, const FString& MappingType, bool bForceRemap, const FString& OpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AutoMapIKRetargetChains requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetIKRetargetChainMapping(const FString& AssetPath, const FString& TargetChainName, const FString& SourceChainName, const FString& OpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRetargetChainMapping requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeIKChainMappingInfo> UUnrealBridgeRigLibrary::ListIKRetargetChainMappings(const FString& AssetPath, const FString& OpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRetargetChainMappings requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeIKChainMappingInfo>{};
}

TArray<FBridgeRigPropertyInfo> UUnrealBridgeRigLibrary::ListIKRetargetOpProperties(const FString& AssetPath, int32 OpIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRetargetOpProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeRigPropertyInfo>{};
}

FBridgeRigPropertyResult UUnrealBridgeRigLibrary::GetIKRetargetOpProperty(const FString& AssetPath, int32 OpIndex, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::GetIKRetargetOpProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigPropertyResult{};
}

bool UUnrealBridgeRigLibrary::SetIKRetargetOpProperty(const FString& AssetPath, int32 OpIndex, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRetargetOpProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeIKRetargetPoseInfo> UUnrealBridgeRigLibrary::ListIKRetargetPoses(const FString& AssetPath, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRetargetPoses requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeIKRetargetPoseInfo>{};
}

FString UUnrealBridgeRigLibrary::CreateIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::CreateIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeRigLibrary::DuplicateIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& NewName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::DuplicateIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeRigLibrary::RenameIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& NewName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RenameIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::RemoveIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetCurrentIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetCurrentIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetIKRetargetPoseBoneRotation(const FString& AssetPath, const FString& Side, const FString& BoneName, const FQuat& RotationOffset)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRetargetPoseBoneRotation requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetIKRetargetPoseRootOffset(const FString& AssetPath, const FString& Side, const FVector& TranslationOffset)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetIKRetargetPoseRootOffset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::ResetIKRetargetPose(const FString& AssetPath, const FString& Side, const FString& PoseName, const TArray<FString>& BoneNames)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ResetIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::AutoAlignIKRetargetPose(const FString& AssetPath, const FString& Side, const TArray<FString>& BoneNames, const FString& Method)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AutoAlignIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FString> UUnrealBridgeRigLibrary::ListIKRetargetProfiles(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ListIKRetargetProfiles requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

bool UUnrealBridgeRigLibrary::SaveCurrentIKRetargetProfile(const FString& AssetPath, const FString& ProfileName, bool bApplySourcePose, bool bApplyTargetPose, bool bForceAllIKOff)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SaveCurrentIKRetargetProfile requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::RemoveIKRetargetProfile(const FString& AssetPath, const FString& ProfileName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::RemoveIKRetargetProfile requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeRigLibrary::SetCurrentIKRetargetProfile(const FString& AssetPath, const FString& ProfileName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::SetCurrentIKRetargetProfile requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeRetargetBatchResult UUnrealBridgeRigLibrary::BatchRetargetAnimations(const FString& RetargeterPath, const TArray<FString>& SourceAssetPaths, const FString& SourceMeshPath, const FString& TargetMeshPath, const FString& DestinationFolder, const FString& Search, const FString& Replace, const FString& Prefix, const FString& Suffix, bool bIncludeReferencedAssets, bool bOverwriteExisting, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::BatchRetargetAnimations requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRetargetBatchResult{};
}

FBridgeRigValidationReport UUnrealBridgeRigLibrary::ValidateIKRetargeter(const FString& AssetPath, bool bInitializeProcessor, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::ValidateIKRetargeter requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRigValidationReport{};
}

FBridgeAnimationQualityReport UUnrealBridgeRigLibrary::AnalyzeAnimationQuality(const FString& AnimationPath, const TArray<FString>& FootBoneNames, int32 NumSamples, float ContactHeightTolerance, float FootSlideSpeedTolerance, float JointAngularDeltaToleranceDegrees, int32 MaxReportedBones)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeRigLibrary::AnalyzeAnimationQuality requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeAnimationQualityReport{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
