// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeStateTreeLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UUnrealBridgeStateTreeLibrary::IsStateTreeApiAvailable()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::IsStateTreeApiAvailable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeStateTreeLibrary::GetLastStateTreeError()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::GetLastStateTreeError requires UE 5.7+ — call ignored on this engine version"));
	return TEXT("StateTree authoring API requires Unreal Engine 5.7+");
}

FBridgeStateTreeCreateResult UUnrealBridgeStateTreeLibrary::CreateStateTree(const FString& AssetPath, const FString& SchemaClassPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::CreateStateTree requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeStateTreeCreateResult{};
}

FBridgeStateTreeAssetInfo UUnrealBridgeStateTreeLibrary::GetStateTreeInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::GetStateTreeInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeStateTreeAssetInfo{};
}

bool UUnrealBridgeStateTreeLibrary::ValidateStateTree(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ValidateStateTree requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeStateTreeCompileResult UUnrealBridgeStateTreeLibrary::CompileStateTree(const FString& AssetPath, bool bRunValidation)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::CompileStateTree requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeStateTreeCompileResult{};
}

TArray<FBridgeStateTreeStateInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeStates(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeStates requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeStateInfo>{};
}

FString UUnrealBridgeStateTreeLibrary::AddStateTreeState(const FString& AssetPath, const FString& ParentStateId, const FString& Name, const FString& StateType, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::AddStateTreeState requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeStateTreeLibrary::RemoveStateTreeState(const FString& AssetPath, const FString& StateId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::RemoveStateTreeState requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::MoveStateTreeState(const FString& AssetPath, const FString& StateId, const FString& NewParentStateId, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::MoveStateTreeState requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeStateType(const FString& AssetPath, const FString& StateId, const FString& StateType)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeStateType requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeStateTreePropertyResult UUnrealBridgeStateTreeLibrary::GetStateTreeStateProperty(const FString& AssetPath, const FString& StateId, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::GetStateTreeStateProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeStateTreePropertyResult{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeStateProperty(const FString& AssetPath, const FString& StateId, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeStateProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeLinkedState(const FString& AssetPath, const FString& StateId, const FString& LinkedStateId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeLinkedState requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeLinkedAsset(const FString& AssetPath, const FString& StateId, const FString& LinkedAssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeLinkedAsset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeStateTreeNodeTypeInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeNodeTypes(const FString& AssetPath, const FString& Kind, bool bIncludeDisallowed)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeNodeTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeNodeTypeInfo>{};
}

TArray<FBridgeStateTreeNodeInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeNodes(const FString& AssetPath, const FString& Scope)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeNodes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeNodeInfo>{};
}

TArray<FBridgeStateTreePropertyInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeNodeProperties(const FString& AssetPath, const FString& NodeId, const FString& DataSource, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeNodeProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreePropertyInfo>{};
}

FString UUnrealBridgeStateTreeLibrary::AddStateTreeNode(const FString& AssetPath, const FString& OwnerId, const FString& Scope, const FString& TypePath, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::AddStateTreeNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeStateTreeLibrary::RemoveStateTreeNode(const FString& AssetPath, const FString& NodeId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::RemoveStateTreeNode requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::MoveStateTreeNode(const FString& AssetPath, const FString& NodeId, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::MoveStateTreeNode requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeStateTreePropertyResult UUnrealBridgeStateTreeLibrary::GetStateTreeNodeProperty(const FString& AssetPath, const FString& NodeId, const FString& DataSource, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::GetStateTreeNodeProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeStateTreePropertyResult{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeNodeProperty(const FString& AssetPath, const FString& NodeId, const FString& DataSource, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeNodeProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeStateTreeTransitionInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeTransitions(const FString& AssetPath, const FString& StateId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeTransitions requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeTransitionInfo>{};
}

FString UUnrealBridgeStateTreeLibrary::AddStateTreeTransition(const FString& AssetPath, const FString& StateId, const FString& Trigger, const FString& TargetType, const FString& TargetStateId, const FString& RequiredEventTag, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::AddStateTreeTransition requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeStateTreeLibrary::RemoveStateTreeTransition(const FString& AssetPath, const FString& TransitionId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::RemoveStateTreeTransition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::MoveStateTreeTransition(const FString& AssetPath, const FString& TransitionId, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::MoveStateTreeTransition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeStateTreePropertyResult UUnrealBridgeStateTreeLibrary::GetStateTreeTransitionProperty(const FString& AssetPath, const FString& TransitionId, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::GetStateTreeTransitionProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeStateTreePropertyResult{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeTransitionProperty(const FString& AssetPath, const FString& TransitionId, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeTransitionProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeTransitionTarget(const FString& AssetPath, const FString& TransitionId, const FString& TargetType, const FString& TargetStateId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeTransitionTarget requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeStateTreeBindingInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeBindings(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeBindings requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeBindingInfo>{};
}

TArray<FBridgeStateTreeBindableStructInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeBindableStructs(const FString& AssetPath, const FString& TargetId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeBindableStructs requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeBindableStructInfo>{};
}

bool UUnrealBridgeStateTreeLibrary::AddStateTreeBinding(const FString& AssetPath, const FString& SourceId, const FString& SourcePath, const FString& TargetId, const FString& TargetPath, bool bOutputBinding)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::AddStateTreeBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::RemoveStateTreeBinding(const FString& AssetPath, const FString& TargetId, const FString& TargetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::RemoveStateTreeBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UUnrealBridgeStateTreeLibrary::ClearStateTreeBindingsForItem(const FString& AssetPath, const FString& ItemId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ClearStateTreeBindingsForItem requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

TArray<FBridgeStateTreeParameterInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeParameters(const FString& AssetPath, const FString& ScopeId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeParameters requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeParameterInfo>{};
}

FString UUnrealBridgeStateTreeLibrary::AddStateTreeRootParameter(const FString& AssetPath, const FString& Name, const FString& Type, const FString& DefaultValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::AddStateTreeRootParameter requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeStateTreeLibrary::RemoveStateTreeRootParameter(const FString& AssetPath, const FString& Name)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::RemoveStateTreeRootParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::RenameStateTreeRootParameter(const FString& AssetPath, const FString& OldName, const FString& NewName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::RenameStateTreeRootParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeParameterValue(const FString& AssetPath, const FString& ScopeId, const FString& Name, const FString& Value, bool bMarkOverridden)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeParameterValue requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeStateTreeBreakpointInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeBreakpoints(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeBreakpoints requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeBreakpointInfo>{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeBreakpoint(const FString& AssetPath, const FString& ItemId, const FString& BreakpointType, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeBreakpoint requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::ClearStateTreeBreakpoints(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ClearStateTreeBreakpoints requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeStateTreeComponentInfo> UUnrealBridgeStateTreeLibrary::ListStateTreeComponents(bool bPIEOnly)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ListStateTreeComponents requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeStateTreeComponentInfo>{};
}

FBridgeStateTreeComponentInfo UUnrealBridgeStateTreeLibrary::GetStateTreeComponentInfo(const FString& ComponentPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::GetStateTreeComponentInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeStateTreeComponentInfo{};
}

bool UUnrealBridgeStateTreeLibrary::SetStateTreeComponentAsset(const FString& ComponentPath, const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SetStateTreeComponentAsset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::ControlStateTreeComponent(const FString& ComponentPath, const FString& Action, const FString& Reason)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::ControlStateTreeComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeStateTreeLibrary::SendStateTreeComponentEvent(const FString& ComponentPath, const FString& EventTag, const FString& Origin)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeStateTreeLibrary::SendStateTreeComponentEvent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
