// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeSmartObjectLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UUnrealBridgeSmartObjectLibrary::IsSmartObjectApiAvailable()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::IsSmartObjectApiAvailable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeSmartObjectLibrary::GetLastSmartObjectError()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetLastSmartObjectError requires UE 5.7+ — call ignored on this engine version"));
	return TEXT("Smart Object API requires Unreal Engine 5.7+");
}

FBridgeSmartObjectCreateResult UUnrealBridgeSmartObjectLibrary::CreateSmartObjectDefinition(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::CreateSmartObjectDefinition requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectCreateResult{};
}

FBridgeSmartObjectDefinitionInfo UUnrealBridgeSmartObjectLibrary::GetSmartObjectDefinitionInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetSmartObjectDefinitionInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectDefinitionInfo{};
}

FBridgeSmartObjectValidationResult UUnrealBridgeSmartObjectLibrary::ValidateSmartObjectDefinition(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ValidateSmartObjectDefinition requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectValidationResult{};
}

TArray<FBridgeSmartObjectPropertyInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectDefinitionProperties(const FString& AssetPath, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectDefinitionProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectPropertyInfo>{};
}

FBridgeSmartObjectPropertyResult UUnrealBridgeSmartObjectLibrary::GetSmartObjectDefinitionProperty(const FString& AssetPath, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetSmartObjectDefinitionProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectPropertyResult{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectDefinitionProperty(const FString& AssetPath, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectDefinitionProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeSmartObjectLibrary::GetSmartObjectTagQueryJson(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetSmartObjectTagQueryJson requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectTagQueryJson(const FString& AssetPath, const FString& QueryJson, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectTagQueryJson requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectTags(const FString& AssetPath, const TArray<FString>& Tags, const FString& SlotId, const FString& TagSet)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectTags requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectTagPolicies(const FString& AssetPath, const FString& UserTagsFilteringPolicy, const FString& ActivityTagsMergingPolicy)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectTagPolicies requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectSlotInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectSlots(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectSlots requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectSlotInfo>{};
}

FString UUnrealBridgeSmartObjectLibrary::AddSmartObjectSlot(const FString& AssetPath, const FString& Name, const FVector& Offset, const FRotator& Rotation, bool bEnabled, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::AddSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeSmartObjectLibrary::DuplicateSmartObjectSlot(const FString& AssetPath, const FString& SourceSlotId, const FString& NewName, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::DuplicateSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectSlot(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::MoveSmartObjectSlot(const FString& AssetPath, const FString& SlotId, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::MoveSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectPropertyInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectSlotProperties(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectSlotProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectPropertyInfo>{};
}

FBridgeSmartObjectPropertyResult UUnrealBridgeSmartObjectLibrary::GetSmartObjectSlotProperty(const FString& AssetPath, const FString& SlotId, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetSmartObjectSlotProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectPropertyResult{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectSlotProperty(const FString& AssetPath, const FString& SlotId, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectSlotProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectTypeInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectBehaviorTypes()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectBehaviorTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectTypeInfo>{};
}

TArray<FBridgeSmartObjectBehaviorInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectBehaviorDefinitions(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectBehaviorDefinitions requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectBehaviorInfo>{};
}

FString UUnrealBridgeSmartObjectLibrary::AddSmartObjectBehaviorDefinition(const FString& AssetPath, const FString& BehaviorClassPath, const FString& SlotId, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::AddSmartObjectBehaviorDefinition requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectBehaviorDefinition(const FString& AssetPath, const FString& BehaviorObjectPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectBehaviorDefinition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::MoveSmartObjectBehaviorDefinition(const FString& AssetPath, const FString& BehaviorObjectPath, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::MoveSmartObjectBehaviorDefinition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectPropertyInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectBehaviorProperties(const FString& AssetPath, const FString& BehaviorObjectPath, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectBehaviorProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectPropertyInfo>{};
}

FBridgeSmartObjectPropertyResult UUnrealBridgeSmartObjectLibrary::GetSmartObjectBehaviorProperty(const FString& AssetPath, const FString& BehaviorObjectPath, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetSmartObjectBehaviorProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectPropertyResult{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectBehaviorProperty(const FString& AssetPath, const FString& BehaviorObjectPath, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectBehaviorProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectTypeInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectDefinitionDataTypes(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectDefinitionDataTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectTypeInfo>{};
}

TArray<FBridgeSmartObjectDefinitionDataInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectDefinitionData(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectDefinitionData requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectDefinitionDataInfo>{};
}

FString UUnrealBridgeSmartObjectLibrary::AddSmartObjectDefinitionData(const FString& AssetPath, const FString& StructTypePath, const FString& SlotId, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::AddSmartObjectDefinitionData requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectDefinitionData(const FString& AssetPath, const FString& DataId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectDefinitionData requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::MoveSmartObjectDefinitionData(const FString& AssetPath, const FString& DataId, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::MoveSmartObjectDefinitionData requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectPropertyInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectDefinitionDataProperties(const FString& AssetPath, const FString& DataId, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectDefinitionDataProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectPropertyInfo>{};
}

FBridgeSmartObjectPropertyResult UUnrealBridgeSmartObjectLibrary::GetSmartObjectDefinitionDataProperty(const FString& AssetPath, const FString& DataId, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetSmartObjectDefinitionDataProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectPropertyResult{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectDefinitionDataProperty(const FString& AssetPath, const FString& DataId, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectDefinitionDataProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectTypeInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectWorldConditionTypes(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectWorldConditionTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectTypeInfo>{};
}

TArray<FBridgeSmartObjectWorldConditionInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectWorldConditions(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectWorldConditions requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectWorldConditionInfo>{};
}

int32 UUnrealBridgeSmartObjectLibrary::AddSmartObjectWorldCondition(const FString& AssetPath, const FString& ConditionStructPath, const FString& SlotId, const FString& Operator, int32 ExpressionDepth, bool bInvert, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::AddSmartObjectWorldCondition requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectWorldCondition(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectWorldCondition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::MoveSmartObjectWorldCondition(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::MoveSmartObjectWorldCondition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectWorldConditionExpression(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, const FString& Operator, int32 ExpressionDepth, bool bInvert)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectWorldConditionExpression requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectPropertyInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectWorldConditionProperties(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectWorldConditionProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectPropertyInfo>{};
}

FBridgeSmartObjectPropertyResult UUnrealBridgeSmartObjectLibrary::GetSmartObjectWorldConditionProperty(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetSmartObjectWorldConditionProperty requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectPropertyResult{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectWorldConditionProperty(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectWorldConditionProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectParameterInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectParameters(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectParameters requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectParameterInfo>{};
}

FString UUnrealBridgeSmartObjectLibrary::AddSmartObjectParameter(const FString& AssetPath, const FString& Name, const FString& Type, const FString& DefaultValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::AddSmartObjectParameter requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectParameter(const FString& AssetPath, const FString& Name)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::RenameSmartObjectParameter(const FString& AssetPath, const FString& OldName, const FString& NewName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::RenameSmartObjectParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectParameterValue(const FString& AssetPath, const FString& Name, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectParameterValue requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectBindableStructInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectBindableStructs(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectBindableStructs requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectBindableStructInfo>{};
}

TArray<FBridgeSmartObjectBindingInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectBindings(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectBindings requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectBindingInfo>{};
}

bool UUnrealBridgeSmartObjectLibrary::AddSmartObjectBinding(const FString& AssetPath, const FString& SourceId, const FString& SourcePath, const FString& TargetId, const FString& TargetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::AddSmartObjectBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectBinding(const FString& AssetPath, const FString& TargetId, const FString& TargetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectComponentInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectComponents(bool bPIEOnly)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectComponents requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectComponentInfo>{};
}

FBridgeSmartObjectComponentInfo UUnrealBridgeSmartObjectLibrary::GetSmartObjectComponentInfo(const FString& ComponentPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::GetSmartObjectComponentInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectComponentInfo{};
}

FString UUnrealBridgeSmartObjectLibrary::AddSmartObjectComponent(const FString& ActorPath, const FString& DefinitionAssetPath, const FString& ComponentName, bool bCanBePartOfCollection, bool bRegisterWithSubsystem)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::AddSmartObjectComponent requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectComponent(const FString& ComponentPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::RemoveSmartObjectComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectComponentDefinition(const FString& ComponentPath, const FString& DefinitionAssetPath, bool bRegisterWithSubsystem)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectComponentDefinition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::ControlSmartObjectComponent(const FString& ComponentPath, const FString& Action)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ControlSmartObjectComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectCollectionInfo> UUnrealBridgeSmartObjectLibrary::ListPersistentSmartObjectCollections(bool bPIEOnly)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListPersistentSmartObjectCollections requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectCollectionInfo>{};
}

FString UUnrealBridgeSmartObjectLibrary::CreatePersistentSmartObjectCollection(const FString& ActorLabel)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::CreatePersistentSmartObjectCollection requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeSmartObjectLibrary::DestroyPersistentSmartObjectCollection(const FString& CollectionActorPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::DestroyPersistentSmartObjectCollection requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::ControlPersistentSmartObjectCollection(const FString& CollectionActorPath, const FString& Action)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ControlPersistentSmartObjectCollection requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectCollectionEntryInfo> UUnrealBridgeSmartObjectLibrary::ListPersistentSmartObjectCollectionEntries(const FString& CollectionActorPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListPersistentSmartObjectCollectionEntries requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectCollectionEntryInfo>{};
}

TArray<FBridgeSmartObjectQueryResult> UUnrealBridgeSmartObjectLibrary::QuerySmartObjects(const FVector& Center, const FVector& Extent, const TArray<FString>& UserTags, const TArray<FString>& ActivityTags, const TArray<FString>& BehaviorClassPaths, const FString& ActivityMatch, const FString& ClaimPriority, bool bEvaluateConditions, bool bIncludeClaimedSlots, bool bIncludeDisabledSlots, const FString& UserActorPath, bool bSortByDistance, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::QuerySmartObjects requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectQueryResult>{};
}

TArray<FBridgeSmartObjectRuntimeSlotInfo> UUnrealBridgeSmartObjectLibrary::ListSmartObjectRuntimeSlots(const FString& SmartObjectHandle, const FString& ComponentPath, const FString& ClaimPriority)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectRuntimeSlots requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectRuntimeSlotInfo>{};
}

FString UUnrealBridgeSmartObjectLibrary::CreateRuntimeSmartObject(const FString& DefinitionAssetPath, const FTransform& Transform, const FString& OwnerActorPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::CreateRuntimeSmartObject requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeSmartObjectLibrary::DestroyRuntimeSmartObject(const FString& SmartObjectHandle)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::DestroyRuntimeSmartObject requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeSmartObjectClaimResult UUnrealBridgeSmartObjectLibrary::ClaimSmartObjectSlot(const FString& SlotHandle, const FString& UserActorPath, const FString& ClaimPriority)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ClaimSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectClaimResult{};
}

FBridgeSmartObjectClaimResult UUnrealBridgeSmartObjectLibrary::OccupySmartObjectClaim(const FString& ClaimToken, const FString& BehaviorClassPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::OccupySmartObjectClaim requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectClaimResult{};
}

bool UUnrealBridgeSmartObjectLibrary::ReleaseSmartObjectClaim(const FString& ClaimToken)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ReleaseSmartObjectClaim requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FBridgeSmartObjectClaimResult> UUnrealBridgeSmartObjectLibrary::ListSmartObjectClaims()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ListSmartObjectClaims requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectClaimResult>{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectRuntimeTags(const FString& Handle, const FString& Scope, const TArray<FString>& Tags, bool bReplace)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectRuntimeTags requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectRuntimeEnabled(const FString& SmartObjectHandle, bool bEnabled, const FString& ReasonTag)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectRuntimeEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::SetSmartObjectRuntimeSlotEnabled(const FString& SlotHandle, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SetSmartObjectRuntimeSlotEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeSmartObjectLibrary::SendSmartObjectSlotEvent(const FString& SlotHandle, const FString& EventTag)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::SendSmartObjectSlotEvent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeSmartObjectEntranceResult UUnrealBridgeSmartObjectLibrary::FindSmartObjectEntrance(const FString& SlotHandle, const FBridgeSmartObjectEntranceRequest& Request)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::FindSmartObjectEntrance requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeSmartObjectEntranceResult{};
}

TArray<FBridgeSmartObjectEntranceResult> UUnrealBridgeSmartObjectLibrary::ValidateSmartObjectDefinitionEntrances(const FString& AssetPath, const FTransform& OwnerTransform, const FBridgeSmartObjectEntranceRequest& Request, const FString& SkipActorPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::ValidateSmartObjectDefinitionEntrances requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeSmartObjectEntranceResult>{};
}

bool UUnrealBridgeSmartObjectLibrary::DebugSmartObjectSubsystem(const FString& Action)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeSmartObjectLibrary::DebugSmartObjectSubsystem requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
